name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.x']

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'
    - name: Install dependencies
      run: |
        gem install bundler
        bundler install
    - name: Validate and lint
      run: |
        bundle exec rake check
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Deploy docs to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v1.0.1
      with:
        target_branch: gh-pages
        build_dir: ./_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
