name: Deploy build

on:
  push:
    # branches:
    # - master
    # tags:
    # - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List directory contents
      run: ls -lhtra
    - name: Setup build for deployment
      run: |
        mkdir -p docs/_build
        cp -r css  _data  fonts  images  _includes  js  _layouts  _pages  _plugins  _sass  _site docs/_build
        cp _config.yml favicon.ico Gemfile Gemfile.lock Rakefile docs/_build
    - name: Deploy build to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        publish_branch: build
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
